version: 0.2

phases:
  install:
    commands:
    - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/1.0.11/terraform_1.0.11_linux_amd64.zip
    - unzip terraform_install.zip -d /usr/bin/
    - chmod +x /usr/bin/terraform
    finally:
      - terraform --version
  build:
    commands:
      - echo ${CODEBUILD_WEBHOOK_TRIGGER##*/}
      - echo ${CODEBUILD_BUILD_ARN}
      - echo ${CODEBUILD_WEBHOOK_EVENT}
      - echo ${CODEBUILD_WEBHOOK_HEAD_REF}
      - echo ${CODEBUILD_WEBHOOK_TRIGGER}
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
      - echo build done!
